version: '3.8'

services:
  backend:
    build: ./backend
    container_name: expense-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped
    networks:
      - expense-network

  frontend:
    build: ./frontend
    container_name: expense-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:5000/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - expense-network

networks:
  expense-network:
    driver: bridge

volumes:
  uploads:
